linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - revive
    - unparam
    - unused
    - whitespace
issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - bodyclose
        - depguard
        - dupl
        - errcheck
        - errorlint
        - funlen
        - gofmt
        - goimports
        - gosec
        - gosimple
        - govet
        - revive
        - unparam
        - unused
        - whitespace
  exclude-dirs:
    - /vendor
