name: format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Prepare Goimports
      run: go install golang.org/x/tools/cmd/goimports@v0.21.0
    - name: Format
      run: make format
