name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: golangci/golangci-lint-action@v6
      with:
        version: v1.57.2
        # Github Action doesn't provide any way to specified which go modules to run to if you have monorepo.
        # this trick the golangci-lint to not running the linter.
        # then we will manually lint using below step.
        args: --help
    - name: Lint
      run: make lint
