name: test

on:
  push:
  pull_request:
  tags:
    - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: |
        for dir in $(find . -maxdepth 1 -type d); do
          dirname=$(basename "$dir")
          if [ "$dirname" != "." ] && [[ "$dirname" != .* ]]; then
            cd "$dirname"
            go test -coverprofile=coverage.out -timeout 30s ./...
            go tool cover -func=coverage.out
            go tool cover -html=coverage.out -o coverage.html
            rm coverage.out coverage.html
            cd ..
          fi
        done
